In [2]:
import numpy as np

In [5]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')

In [11]:
np.isnan(lending_co_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [12]:
np.isnan(lending_co_data_numeric).sum()

0

In [18]:
lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-NAN.csv',delimiter=',',filling_values=0)

In [19]:
np.isnan(lending_co_data_numeric_nan).sum()

0

In [20]:
temporary_fill=np.nanmax(lending_co_data_numeric_nan).round(2)+1

In [21]:
temporary_fill

1.0

In [6]:
lending_co_data_numeric

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]])

In [22]:
lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-NAN.csv',delimiter=',',filling_values=temporary_fill)

In [24]:
np.isnan(lending_co_data_numeric_nan).sum()

0

### substituting the missing values

In [32]:
lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-NAN.csv',delimiter=',')
lending_co_data_numeric_nan

array([nan, nan, nan, ..., nan, nan, nan])

In [34]:
lending_co_data_numeric = np.genfromtxt('Lending-Company-Numeric.csv',delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [35]:
lending_co_data_numeric.shape

(1043, 6)

### reshaping

In [36]:
np.reshape(lending_co_data_numeric,(6,1043))

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [38]:
np.transpose(lending_co_data_numeric)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]])

In [42]:
np.reshape(lending_co_data_numeric,(1,1,2,3,1043))

array([[[[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
          [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
          [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

         [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
          [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
          [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]]]])

In [43]:
 lending_co_data_numeric_2=np.reshape(lending_co_data_numeric,(6,1043))

In [44]:
lending_co_data_numeric_2

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

### removing values

In [45]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [48]:
np.delete(lending_co_data_numeric,0)

array([   40.,   365.,  3121., ...,  4601.,  4601., 16600.])

In [49]:
np.delete(lending_co_data_numeric,0).shape

(6257,)

In [55]:
np.delete(lending_co_data_numeric,[0,2,4],axis=1)

array([[   40.,  3121., 13621.],
       [   40.,  3061., 15041.],
       [   40.,  2160., 15340.],
       ...,
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.],
       [   40.,  4601., 16600.]])

### sorting

In [58]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [59]:
np.sort(lending_co_data_numeric).shape

(1043, 6)

In [67]:
np.sort(lending_co_data_numeric,axis=None)

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.])

In [64]:
np.set_printoptions(suppress=True)

In [68]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [71]:
-np.sort(-lending_co_data_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]])

In [72]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [73]:
np.sort(lending_co_data_numeric[:,3])

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.])

In [74]:
lending_co_data_numeric[:,3].sort()

In [75]:
lending_co_data_numeric

array([[ 2000.,    40.,   365., -2870.,  4241., 13621.],
       [ 2000.,    40.,   365., -2550.,  4171., 15041.],
       [ 1000.,    40.,   365., -2450.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., 16751.,  5001., 16600.],
       [ 1000.,    40.,   365., 17650.,  3320., 15600.],
       [ 2000.,    40.,   365., 19001.,  4601., 16600.]])

### np.argsort()

In [76]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [77]:
np.argsort(lending_co_data_numeric)

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]], dtype=int64)

In [78]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [80]:
np.argsort(lending_co_data_numeric,axis=0)

array([[ 537,  443,    0,   32,   32,  482],
       [ 639,  327,  687,  166,  166,  493],
       [ 849,  432,  688,   85,   85,  166],
       ...,
       [  27,  326,  355,  568, 1019,  568],
       [ 277,   27,  357,  718, 1033,  534],
       [ 420,  408, 1042,  912,  912,   27]], dtype=int64)

In [81]:
np.argsort(lending_co_data_numeric[:,0])

array([537, 639, 849, ...,  27, 277, 420], dtype=int64)

### np.argwhere()

In [3]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [4]:
np.argwhere(lending_co_data_numeric)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]], dtype=int64)

In [5]:
np.argwhere(lending_co_data_numeric==False)

array([[116,   4],
       [430,   3]], dtype=int64)

In [6]:
lending_co_data_numeric[430]

array([1000.,   50.,  365.,    0.,  550., 5650.])

In [7]:
np.argwhere(lending_co_data_numeric%2==0)

array([[   0,    0],
       [   0,    1],
       [   1,    0],
       ...,
       [1042,    0],
       [1042,    1],
       [1042,    5]], dtype=int64)

In [8]:
lending_co_data_numeric.argwhere()

AttributeError: 'numpy.ndarray' object has no attribute 'argwhere'

In [10]:
np.isnan(lending_co_data_numeric).sum()

0

In [11]:
lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-NAN.csv',delimiter=';')
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [13]:
np.argwhere(np.isnan(lending_co_data_numeric_nan))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [14]:
lending_co_data_numeric_nan[175]

array([ 2000.,    nan,    nan,  1851.,  3051., 13561.])

In [15]:
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_nan)):
    lending_co_data_numeric_nan[array_index[0],array_index[1]]=0

In [16]:
lending_co_data_numeric_nan[175]

array([ 2000.,     0.,     0.,  1851.,  3051., 13561.])

### shuffling

In [18]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [19]:
np.random.shuffle(lending_co_data_numeric)

In [20]:
lending_co_data_numeric

array([[ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.]])

In [21]:
np.random.shuffle(lending_co_data_numeric)

In [22]:
lending_co_data_numeric

array([[ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.]])

In [23]:
np.random.shuffle(lending_co_data_numeric)

In [24]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.]])

In [25]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [26]:
from numpy.random import shuffle

In [27]:
shuffle(lending_co_data_numeric)

In [28]:
lending_co_data_numeric

array([[ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [29]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [34]:
array_rg=gen(pcg())
array_rg=shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

### casting

In [35]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [37]:
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       [ 2000,    40,   365,  3041,  4241, 15321],
       [ 2000,    50,   365,  3470,  4820, 13720],
       [ 2000,    40,   365,  3201,  4141, 14141],
       [ 2000,    50,   365,  1851,  3251, 17701],
       [ 2000,    40,   365,  3971,  4131, 15351]])

In [38]:
lending_co_data_numeric.astype(dtype = np.str)

<ipython-input-38-25dbd518c046>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric.astype(dtype = np.str)


array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ['2000.0', '40.0', '365.0', '3041.0', '4241.0', '15321.0'],
       ['2000.0', '50.0', '365.0', '3470.0', '4820.0', '13720.0'],
       ['2000.0', '40.0', '365.0', '3201.0', '4141.0', '14141.0'],
       ['2000.0', '50.0', '365.0', '1851.0', '3251.0', '17701.0'],
       ['2000.0', '40.0', '365.0', '3971.0', '4131.0', '15351.0']],
      dtype='<U32')

In [39]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [40]:
type(lending_co_data_numeric)

numpy.ndarray

In [41]:
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       [ 2000,    40,   365,  3041,  4241, 15321],
       [ 2000,    50,   365,  3470,  4820, 13720],
       [ 2000,    40,   365,  3201,  4141, 14141],
       [ 2000,    50,   365,  1851,  3251, 17701],
       [ 2000,    40,   365,  3971,  4131, 15351]])

### string to float then float to integer data  type

In [42]:
lending_co_data_numeric.astype(dtype = np.str)

<ipython-input-42-25dbd518c046>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric.astype(dtype = np.str)


array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ['2000.0', '40.0', '365.0', '3041.0', '4241.0', '15321.0'],
       ['2000.0', '50.0', '365.0', '3470.0', '4820.0', '13720.0'],
       ['2000.0', '40.0', '365.0', '3201.0', '4141.0', '14141.0'],
       ['2000.0', '50.0', '365.0', '1851.0', '3251.0', '17701.0'],
       ['2000.0', '40.0', '365.0', '3971.0', '4131.0', '15351.0']],
      dtype='<U32')

In [43]:
lending_co_data_numeric.astype(dtype = np.float32)(dtype=np.int32)

TypeError: 'numpy.ndarray' object is not callable

### stripping Values

In [44]:
lending_co_total_price=np.genfromtxt('Lending-Company-Total-Price.csv',delimiter=',',dtype=np.str,usecols=[1,2,4])


<ipython-input-44-ec7200e630e0>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_total_price=np.genfromtxt('Lending-Company-Total-Price.csv',delimiter=',',dtype=np.str,usecols=[1,2,4])


In [45]:
lending_co_total_price

array([['StringID', 'Product', 'Location'],
       ['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

In [46]:
np.chararray.strip(lending_co_total_price[:,0],'id')

chararray(['StringID', '_1', '_2', '_3', '_4', '_5', '_6', '_7', '_8',
           '_9', '_10', '_11', '_12', '_13', '_14', '_15', '_16', '_17',
           '_18', '_19', '_20', '_21', '_22', '_23', '_24', '_25', '_26',
           '_27', '_28', '_29', '_30', '_31', '_32', '_33', '_34', '_35',
           '_36', '_37', '_38', '_39', '_40', '_41', '_42', '_43', '_44',
           '_45', '_46', '_47', '_48', '_49', '_50', '_51', '_52', '_53',
           '_54', '_55', '_56', '_57', '_58', '_59', '_60', '_61', '_62',
           '_63', '_64', '_65', '_66', '_67', '_68', '_69', '_70', '_71',
           '_72', '_73', '_74', '_75', '_76', '_77', '_78', '_79', '_80',
           '_81', '_82', '_83', '_84', '_85', '_86', '_87', '_88', '_89',
           '_90', '_91', '_92', '_93', '_94', '_95', '_96', '_97', '_98',
           '_99', '_100', '_101', '_102', '_103', '_104', '_105', '_106',
           '_107', '_108', '_109', '_110', '_111', '_112', '_113', '_114',
           '_115', '_116', '_117', '_118'

In [49]:
lending_co_total_price[:,0]=np.chararray.strip(lending_co_total_price[:,0],'id')

In [50]:
lending_co_total_price

array([['StringID', 'Product', 'Location'],
       ['_1', 'Product B', 'Location 2'],
       ['_2', 'Product B', 'Location 3'],
       ...,
       ['_413', 'Product B', 'Location 135'],
       ['_414', 'Product C', 'Location 200'],
       ['_415', 'Product A', 'Location 8']], dtype='<U12')

### stacking

In [3]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [4]:
lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-NAN.csv',delimiter=';')
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [9]:
np.stack((lending_co_data_numeric[:,0],lending_co_data_numeric[:,1]))

array([[2000., 2000., 1000., 2000., 2000., 2000., 2000., 2000.],
       [  40.,   40.,   40.,   40.,   50.,   40.,   50.,   40.]])

In [7]:
np.transpose(lending_co_data_numeric[:,:2])

array([[2000., 2000., 1000., 2000., 2000., 2000., 2000., 2000.],
       [  40.,   40.,   40.,   40.,   50.,   40.,   50.,   40.]])

In [11]:
np.stack((lending_co_data_numeric[:,0],lending_co_data_numeric[:,1],lending_co_data_numeric[:,:2]),axis=1)

ValueError: all input arrays must have the same shape

In [15]:
lending_co_data_numeric_nan.shape

(1043, 6)

In [21]:
np.hstack((lending_co_data_numeric,lending_co_data_numeric))

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
          365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.,  2000.,    40.,
          365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.,  1000.,    40.,
          365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.,  2000.,    40.,
          365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.,  2000.,    50.,
          365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.,  2000.,    40.,
          365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.,  2000.,    50.,
          365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.,  2000.,    40.,
          365.,  3971.,  4131., 15351.]])

In [22]:
np.dstack((lending_co_data_numeric,lending_co_data_numeric))

array([[[ 2000.,  2000.],
        [   40.,    40.],
        [  365.,   365.],
        [ 3121.,  3121.],
        [ 4241.,  4241.],
        [13621., 13621.]],

       [[ 2000.,  2000.],
        [   40.,    40.],
        [  365.,   365.],
        [ 3061.,  3061.],
        [ 4171.,  4171.],
        [15041., 15041.]],

       [[ 1000.,  1000.],
        [   40.,    40.],
        [  365.,   365.],
        [ 2160.,  2160.],
        [ 3280.,  3280.],
        [15340., 15340.]],

       [[ 2000.,  2000.],
        [   40.,    40.],
        [  365.,   365.],
        [ 3041.,  3041.],
        [ 4241.,  4241.],
        [15321., 15321.]],

       [[ 2000.,  2000.],
        [   50.,    50.],
        [  365.,   365.],
        [ 3470.,  3470.],
        [ 4820.,  4820.],
        [13720., 13720.]],

       [[ 2000.,  2000.],
        [   40.,    40.],
        [  365.,   365.],
        [ 3201.,  3201.],
        [ 4141.,  4141.],
        [14141., 14141.]],

       [[ 2000.,  2000.],
        [   50.,    50.],


In [24]:
np.hstack((lending_co_data_numeric,lending_co_data_numeric))[0,:,0]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [25]:
np.stack((lending_co_data_numeric,lending_co_data_numeric))

array([[[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
        [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
        [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
        [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
        [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
        [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
        [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
        [ 2000.,    40.,   365.,  3971.,  4131., 15351.]],

       [[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
        [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
        [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
        [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
        [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
        [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
        [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
        [ 2000.,    40.,   365.,  3971.,  4131., 15351.]]])

In [26]:
array_exampl_1=np.array([[1,2,3,4],[4,5,6,7],[2,3,4,5],[7,8,9,5]])
array_exampl_2=array_exampl_1*2

In [27]:
array_exampl_2

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [ 4,  6,  8, 10],
       [14, 16, 18, 10]])

In [28]:
array_exampl_1

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 3, 4, 5],
       [7, 8, 9, 5]])

In [31]:
np.dstack((array_exampl_1,array_exampl_2))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6],
        [ 4,  8]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12],
        [ 7, 14]],

       [[ 2,  4],
        [ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18],
        [ 5, 10]]])

In [34]:
np.dstack((array_exampl_1,array_exampl_2))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6],
        [ 4,  8]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12],
        [ 7, 14]],

       [[ 2,  4],
        [ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18],
        [ 5, 10]]])

### concatenate

In [35]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [37]:
np.concatenate((lending_co_data_numeric[0,:],lending_co_data_numeric[1,:]))

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3061.,  4171., 15041.])

In [39]:
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_nan))

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [43]:
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_nan),axis=0)

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [44]:
array_exampl_1=np.array([[1,2,3,4],[4,5,6,7],[2,3,4,5],[7,8,9,5]])
array_exampl_2=array_exampl_1*2

In [50]:
np.concatenate((array_exampl_1,array_exampl_2),axis=1)

array([[ 1,  2,  3,  4,  2,  4,  6,  8],
       [ 4,  5,  6,  7,  8, 10, 12, 14],
       [ 2,  3,  4,  5,  4,  6,  8, 10],
       [ 7,  8,  9,  5, 14, 16, 18, 10]])

### unique

In [51]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric.csv',delimiter=',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [52]:
np.unique(lending_co_data_numeric[:,1])

array([40., 50.])