In [1]:
import numpy as np

In [2]:
array_empty=np.empty(shape=(2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_0s=np.zeros(shape=(2,3),dtype=np.int32)
array_0s

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
array_1s=np.ones(shape=(2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
 array_full=np.full(shape=(2,3), fill_value= 10)
array_full

array([[10, 10, 10],
       [10, 10, 10]])

In [19]:
 matrix=np.array([[1,2,3,4,5],[6,7,8,9,10],[2,4,5,6,7]])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2,  4,  5,  6,  7]])

In [20]:
array_0s_like=np.empty_like(matrix)
array_0s_like

array([[      0,       0,       0,       0,       0],
       [      0,       0,       0,       0,       0],
       [    856,       0,       0, 7209071,       0]])

In [21]:
array_1s_like=np.ones_like(matrix)
array_1s_like

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
array__like=np.ones_like(matrix)
array_1s_like

### np.arrange()

In [22]:
list(range(40))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39]

In [23]:
array_rng= np.arange(20)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
array_rng= np.arange(start=5,stop=20,step=3,dtype=float)
array_rng

array([ 5.,  8., 11., 14., 17.])

### random variables

In [28]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg



In [30]:
 array_RG=gen(pcg(seed=365))
array_RG.normal(size=(5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [31]:
 array_RG=gen(pcg())
array_RG.normal(size=(5,5))

array([[ 0.96341256,  0.35755391, -0.98361271,  1.47705789, -1.82378962],
       [ 0.28897591,  0.90551283,  2.64600894, -0.47107154,  0.64706026],
       [-1.46758874, -0.06617696, -1.25264116,  1.78267517, -0.80537426],
       [-0.57641269, -0.0470363 ,  0.15785501, -0.59676735, -0.75349736],
       [ 1.72018856,  0.42317754,  0.27630706,  0.64629476,  0.969876  ]])

In [34]:
 array_RG=gen(pcg(seed=365))
array_RG.integers(low=10,high=100 ,size=(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]], dtype=int64)

In [36]:
 array_RG=gen(pcg(seed=365))
array_RG.random(size=(5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [37]:
 array_RG=gen(pcg(seed=365))
array_RG.choice([1,2,3,4,5] ,size=(5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [40]:
  array_RG=gen(pcg(seed=365))
array_RG.poisson(lam=10 ,size=(5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]], dtype=int64)

In [41]:
 array_RG=gen(pcg(seed=365))
array_RG.binomial(n=100,p=0.4 ,size=(5,5))

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]], dtype=int64)

In [42]:
 array_RG=gen(pcg(seed=365))
array_RG.logistic(loc=9,scale=1.2 ,size=(5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])