In [36]:
import numpy as np

In [3]:
 lending_co_data_numeric_1=np.loadtxt('Lending-Company-Numeric-Data.csv',delimiter = ',')
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [6]:
 lending_co_data_numeric_2=np.genfromtxt('Lending-Company-Numeric-Data.csv',delimiter = ',')
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [7]:
np.array_equal(lending_co_data_numeric_1,lending_co_data_numeric_2)

True

In [21]:
lending_co_data_numeric_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter =';',dtype=np.str)
lending_co_data_numeric_NAN                                      

<ipython-input-21-5200d1f98e0b>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter =';',dtype=np.str)


array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

In [20]:
lending_co_data_numeric_NAN=np.loadtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter =';',dtype=np.str)
lending_co_data_numeric_NAN                                      

<ipython-input-20-89ea5af80f95>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric_NAN=np.loadtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter =';',dtype=np.str)


array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

### simple cleaning the data

In [22]:
lending_co_data_numeric_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter =';')
lending_co_data_numeric_NAN                                      

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [24]:
lending_co_data_numeric_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter =';',skip_header=2)
lending_co_data_numeric_NAN                                      

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [25]:
lending_co_data_numeric_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter =';',skip_footer=2)
lending_co_data_numeric_NAN                                      

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [31]:
lending_co_data_numeric_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv'
                                          ,delimiter =';'
                                          ,usecols=(4,1,5),skip_header=2 ,skip_footer=2,unpack=True)
lending_co_data_numeric_NAN                                      

array([[ 3280.,  4241.,  4820., ...,    nan,  5440.,  5001.],
       [   40.,    40.,    50., ...,    40.,    40.,    40.],
       [15340., 15321., 13720., ..., 16600., 16600., 16600.]])

##string vs number vs object

In [44]:
lending_co_lt=np.genfromtxt('Lending-co-Lt.csv',delimiter=',',dtype=np.object)
lending_co_lt

<ipython-input-44-7c094e7713dd>:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_lt=np.genfromtxt('Lending-co-Lt.csv',delimiter=',',dtype=np.object)


array([[b'LoanID', b'StringID', b'Product', ..., b'Location', b'Region',
        b'TotalPrice'],
       [b'1', b'id_1', b'Product B', ..., b'Location 2', b'Region 2',
        b'16600.0'],
       [b'2', b'id_2', b'Product B', ..., b'Location 3', b'', b'16600.0'],
       ...,
       [b'1041', b'id_1041', b'Product B', ..., b'Location 23',
        b'Region 4', b'16600.0'],
       [b'1042', b'id_1042', b'Product C', ..., b'Location 52',
        b'Region 6', b'15600.0'],
       [b'1043', b'id_1043', b'Product B', ..., b'Location 142',
        b'Region 6', b'16600.0']], dtype=object)

In [42]:
lending_co_lt[0,0]+lending_co_lt[0,1]

-2