In [2]:
import numpy as np

#indexing 


In [3]:
array_a=np.array([[1,2,3],[2,3,4]])
array_a

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
array_a[0][2]

3

In [8]:
array_a[1][0]

2

In [9]:
array_a[0,2]

3

In [12]:
array_a[:,0]

array([1, 2])

In [13]:
array_a[0][-1]

3

In [15]:
array_a[-0]

array([1, 2, 3])

### assigning values

In [17]:
array_a[0][2]=8

In [19]:
array_a

array([[1, 2, 8],
       [2, 3, 4]])

In [20]:
array_a[:,0]=9
array_a

array([[9, 2, 8],
       [9, 3, 4]])

In [21]:
array_a[:]=9

In [22]:
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [23]:
array_a=np.array([[1,2,3],[2,3,4]])
array_a

array([[1, 2, 3],
       [2, 3, 4]])

### element wise properties

In [24]:
array_b=array_a

In [25]:
array_b

array([[1, 2, 3],
       [2, 3, 4]])

In [26]:
array_a=np.array([1,2,5])

In [27]:
array_a

array([1, 2, 5])

In [28]:
array_a+2

array([3, 4, 7])

In [29]:
array_b*2

array([[2, 4, 6],
       [4, 6, 8]])

In [32]:
array_a+array_b

array([[2, 4, 8],
       [3, 5, 9]])

### data types of numpy

In [41]:
array_a=np.array([[1,2,3],[2,3,4]],dtype =np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [2.+0.j, 3.+0.j, 4.+0.j]], dtype=complex64)

In [42]:
array_a=np.array([[1,2,3],[2,3,4]],dtype =np.float64)
array_a

array([[1., 2., 3.],
       [2., 3., 4.]])

In [44]:
array_a=np.array([[1,0,3],[2,3,4]],dtype =np.bool)
array_a

<ipython-input-44-5bcdf7c197aa>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a=np.array([[1,0,3],[2,3,4]],dtype =np.bool)


array([[ True, False,  True],
       [ True,  True,  True]])

In [49]:
array_a=np.array([[1,0,33],[2,3,4]],dtype =np.str)
array_a

<ipython-input-49-85e9c1e72a16>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a=np.array([[1,0,33],[2,3,4]],dtype =np.str)


array([['1', '0', '33'],
       ['2', '3', '4']], dtype='<U2')

### broadcasting

In [50]:
array_a=np.array([1,2,5])
array_a

array([1, 2, 5])

In [51]:
array_b=np.array([[1],
                [2]])
array_b

array([[1],
       [2]])

In [54]:
array_c=np.array([[1,2,5],[6,7,8]])
array_c

array([[1, 2, 5],
       [6, 7, 8]])

In [58]:
np.add(array_b,array_c, dtype =np.float64)

array([[ 2.,  3.,  6.],
       [ 8.,  9., 10.]])

In [64]:
   np.mean(array_c,axis=1)

array([2.66666667, 7.        ])

###slicing


In [3]:
array_a=np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_a[2:]

array([], shape=(0, 3), dtype=int32)

In [9]:
array_a[1]

array([4, 5, 6])

In [10]:
array_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
array_a[1:]

array([[4, 5, 6]])

In [19]:
array_a[0:,1:]

array([[2, 3],
       [5, 6]])

In [60]:
array_c

array([[1, 2, 5],
       [6, 7, 8]])