In [1]:
import numpy as np

In [8]:
array_a=np.array([1,3,45,6])
array_a

array([ 1,  3, 45,  6])

In [3]:
array_b=np.array([[1,3,45,6],[12,3,4,5]])
array_b

array([[ 1,  3, 45,  6],
       [12,  3,  4,  5]])

In [11]:
np.mean(array_b,axis=0)

array([ 6.5,  3. , 24.5,  5.5])

In [12]:
type(array_a)

numpy.ndarray

In [20]:
array_b.shape[0]

2

In [24]:
array_c=np.array([13])

In [25]:
array_c.shape

(1,)

#list vs array

In [29]:
list=[1,2,3,4,5],[6,7,8,9,10]

In [30]:
list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

In [31]:
len(list)

2

In [32]:
array_d=np.array(list)

In [33]:
array_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
type(array_d)

numpy.ndarray

In [35]:
print(list)

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])


In [36]:
print(array_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
array_d.shape

(2, 5)

In [39]:
import math

In [42]:
np.sqrt(array_b)

array([[1.        , 1.73205081, 6.70820393, 2.44948974],
       [3.46410162, 1.73205081, 2.        , 2.23606798]])