### 

### step wise slicing 

In [1]:
import numpy as np

In [2]:
array=np.array([[1,1,2,2,4],[2,3,4,5,1],[3,2,1,4,5]])
array

array([[1, 1, 2, 2, 4],
       [2, 3, 4, 5, 1],
       [3, 2, 1, 4, 5]])

In [3]:
array[:]

array([[1, 1, 2, 2, 4],
       [2, 3, 4, 5, 1],
       [3, 2, 1, 4, 5]])

In [6]:
array[::2,::]

array([[1, 1, 2, 2, 4],
       [3, 2, 1, 4, 5]])

In [7]:
array[::,::2]

array([[1, 2, 4],
       [2, 4, 1],
       [3, 1, 5]])

In [8]:
array[::2,::2]

array([[1, 2, 4],
       [3, 1, 5]])

In [11]:
array[::-2,::-2]

array([[5, 1, 3],
       [4, 2, 1]])

### conditional slicing

In [12]:
matrix=array
matrix

array([[1, 1, 2, 2, 4],
       [2, 3, 4, 5, 1],
       [3, 2, 1, 4, 5]])

In [22]:
matrix[(matrix[:]%2==0)|(matrix[:]>3)]

array([2, 2, 4, 2, 4, 5, 2, 4, 5])

In [24]:
matrix[(matrix[:]%2==0)&(matrix[:]<=4)]

array([2, 2, 4, 2, 4, 2, 4])

dimensions and squeeze function### 

In [25]:
matrix

array([[1, 1, 2, 2, 4],
       [2, 3, 4, 5, 1],
       [3, 2, 1, 4, 5]])